In [1]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var+3
print(varadd)

[4 5 6 7]


In [2]:
var = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])
varad=var+var1
print(varad)
print(var1+var)

[2 4 6 8]
[2 4 6 8]


In [4]:
var = np.array([1,2,3,4])
varsub = var-3
print(varsub)

[-2 -1  0  1]


In [5]:
var = np.array([1,2,3,4])
varmul = var*3
print(varmul)

[ 3  6  9 12]


In [6]:
var = np.array([1,2,3,4])
vardiv = var/3
print(vardiv)

[0.33333333 0.66666667 1.         1.33333333]


In [7]:
var = np.array([1,2,3,4])
vardiv = var%3
print(vardiv)

[1 2 0 1]


In [9]:
import numpy as np

var = np.array([1, 2, 3, 4])
var1 = np.array([1, 2, 3, 4])

varadd = np.add(var, var1)
varsub = np.subtract(var, var1)
varmul = np.multiply(var, var1)
varmod = np.mod(var, var1)
varpw = np.power(var, var1)
varrec = np.reciprocal(var1)  

print("var:", var)
print("var1:", var1)
print("varadd:", varadd)
print("varsub:", varsub)
print("varmul:", varmul)
print("varmod:", varmod)
print("varpw:", varpw)
print("varrec:", varrec)


var: [1 2 3 4]
var1: [1 2 3 4]
varadd: [2 4 6 8]
varsub: [0 0 0 0]
varmul: [ 1  4  9 16]
varmod: [0 0 0 0]
varpw: [  1   4  27 256]
varrec: [1 0 0 0]
