In [2]:
import numpy as np
var = np.array([1,2,3,4,5,3,2])
print("MIN : ", np.min(var))
print("Max : ", np.max(var))
print("MIN with index: ", np.argmin(var))
print("Max with index: ", np.argmax(var))

MIN :  1
Max :  5
MIN with index:  0
Max with index:  4


In [3]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))#row wise
print(np.min(var1,axis=1))#column wise

[2 1 3]
[1 5]


In [4]:
var = np.array([1,2,3,4,5,3,2])
print("square", np.sqrt(var))


square [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [5]:
var = np.array([1,2,3])
print(np.sin(var))
print(np.cos(var))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [6]:
var = np.array([1,2,3])
print(np.cumsum(var))

[1 3 6]


In [7]:
var = np.array([1,2,3,4])
print(np.cumsum(var))

[ 1  3  6 10]
