In [9]:
import numpy as np
var = np.array([1,2,3,4])
co = var.copy()
var[1]=234
print(var)
print(co)

[  1 234   3   4]
[1 2 3 4]


In [7]:
import numpy as np
var1 = np.array([1,2,3,4])
vi = var.view
print(var)
var1 [1]=23
print(vi)

[ 1 23  3  4]
<built-in method view of numpy.ndarray object at 0x000001FA5C2938D0>
