In [1]:
import numpy as np
var=np.array([1,2,3,4])
print(var.dtype)

int32


In [2]:
var=np.array([1.0,2.0,3.0,4.0])
print(var.dtype)

float64


In [3]:
var=np.array(["a","b","g","f"])
print(var.dtype)

<U1


In [4]:
var=np.array(["a","b","g","f",1.0,2.0,3.0,4.0])
print(var.dtype)

<U32


In [5]:
var=np.array(["a","b","g","f",1,2,3,4])
print(var.dtype)

<U11


In [14]:
var=np.array([1,2,3,4],dtype="f")
print(var.dtype,"\n",var)
print(var)

float32 
 [1. 2. 3. 4.]
[1. 2. 3. 4.]


In [15]:
x = np.array([1,2,3,4])
nw = np.float32(x)
print(x.dtype)
print(nw.dtype)
print(x)
print(nw)

int32
float32
[1 2 3 4]
[1. 2. 3. 4.]


In [17]:
nw2 = np.int32(nw)
print(nw2)

[1 2 3 4]


In [18]:
x3 = np.array([1,2,3,4])
nw3 = x3.astype(float)
print(x3)
print(nw3)

[1 2 3 4]
[1. 2. 3. 4.]
