In [2]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
x = np.array([[1,2,3,4],[1,2,3,4]])
print(x)
print(x.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [7]:
x = np.array([[[1,2,3,4],[1,2,3,4],[12,2,3,4]]])
print(x)
print(x.ndim)

[[[ 1  2  3  4]
  [ 1  2  3  4]
  [12  2  3  4]]]
3


In [15]:
x = np.array([1,2,3,4], ndmin=10)
print(x)
print(x.ndim)


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
