In [7]:
import numpy as np
var = np.array([1,2,3,4,2,5,2,5,6,7,3])
x = np.where(var==2)
print(x)

(array([1, 4, 6], dtype=int64),)


In [8]:
var = np.array([1,2,3,4,2,5,2,5,6,7,3])
x = np.where((var%2)==0)
print(x)

(array([1, 3, 4, 6, 8], dtype=int64),)


In [11]:
var1 = np.array([1,2,3,4,5,6,7,8])
x1 = np.searchsorted(var1,5)
print(x1)

4


In [13]:
x1 = np.searchsorted(var1,5,side="right")
x2 = np.searchsorted(var1,[5,6,7])
print(x1,"\n",x2)

5 
 [4 5 6]


In [14]:
var1 = np.array([4,2,3,1,12,5,22,52,6,7])
print(np.sort(var1))

[ 1  2  3  4  5  6  7 12 22 52]


In [15]:
var2 = np.array(["z","a","e","b","s"])
print(np.sort(var2))

['a' 'b' 'e' 's' 'z']


In [16]:
var=np.array([[4,2,4],[1,12,5],[22,52,6]])
print(np.sort(var))

[[ 2  4  4]
 [ 1  5 12]
 [ 6 22 52]]


In [17]:
var = np.array(["a","b","c","d"])
f = [True,False,False,True]
x = var[f]
print(x)

['a' 'd']


(array([ 1,  2,  3,  4,  5,  6,  7, 12, 22, 52]), array([3, 1, 2, 0, 5, 8, 9, 4, 6, 7], dtype=int64))
