In [2]:
import numpy as np
var = np.array([1,2,3,4,5])
x = np.unique(var,return_index=True)
print(x)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4], dtype=int64))


In [3]:
var2 = np.array([1,2,3,4,5])
y = np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 1]]


In [4]:
'''c = c_style
f = Fortran_style
A = Fortran * contigous in memory
k = flatten 'a'+'''

"c = c_style\nf = Fortran_style\nA = Fortran * contigous in memory\nk = flatten 'a'+"

In [6]:
import numpy as np

var2 = np.array([1, 2, 3, 4, 5, 6])
print("Flatten: ", var2.flatten(order="F"))
print("Ravel: ", np.ravel(var2, order="K"))


Flatten:  [1 2 3 4 5 6]
Ravel:  [1 2 3 4 5 6]
