In [11]:
import numpy as np
ar_zero = np.zeros(4)

print(ar_zero)

[0. 0. 0. 0.]


In [9]:
ar_zero1 = np.zeros((3,4),dtype=int)

print(ar_zero1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
ar_zero = np.ones(4)

print(ar_zero)

[1. 1. 1. 1.]


In [12]:
ar_zero1 = np.ones((3,4),dtype=int)

print(ar_zero1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
x = np.empty(4)
print(x)
#it stores previously run program

[1. 1. 1. 1.]


In [18]:
var = np.arange(4)
print(var)

[0 1 2 3]


In [24]:
var = np.eye(4,dtype=int)
print(var)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [26]:
var = np.eye(3,5)
var

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [30]:
var = np.linspace(1,20,num=5)
print(var)

[ 1.    5.75 10.5  15.25 20.  ]
