In [2]:
import numpy as np
var = np.array([1,2,3,4])
print(var[1])
print(var[-3])

2
2


In [2]:
var = np.array([[8,9,10,11,],[2,5,6,4]])
print(var)
print()
print(var[0,2])
print(var[1,0])

[[ 8  9 10 11]
 [ 2  5  6  4]]

10
2


In [7]:

var = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(var)
print(var.ndim)
print(var[0,2,0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
7


In [3]:

var = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


print(var)
print(var.ndim)
print(var[0,1,0])
print(var[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
4
12
