In [2]:
import numpy as np

zx=np.array([1,2,3,4])
print(zx)

zx = np.insert (zx, 2, 22)
print(zx)


[1 2 3 4]
[ 1  2 22  3  4]


In [3]:
var1 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var1,2,6,axis=1)
print(v1)

[[1 2 6 3]
 [1 2 6 3]]


In [9]:
var2 = np.array([1,2,3,4])
x = np.append(var2,6.5)
print(x)


x2 = np.append([[25, 22]], [[30, 28]], axis=0)
print(x2)


[1.  2.  3.  4.  6.5]
[[25 22]
 [30 28]]


In [10]:
var1 = np.array([1,2,3,4])
print(var1)
d = np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]
