In [1]:
import numpy as np 
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])
arr = np.concatenate((var,var1))
print (arr)

[1 2 3 4 9 8 7 6]


In [5]:
import numpy as np 
var = np.array([[1,2],[3,4]])
var1 = np.array([[9,8],[7,6]])
arr = np.concatenate((var,var1),axis=0)
print (arr)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [8]:
import numpy as np 
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])
arr = np.stack((var,var1),axis=1)
print (arr)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [9]:
var3 = np.array([1,2,3,4,5])
x = np.array_split(var3,3)
print(x)

[array([1, 2]), array([3, 4]), array([5])]
