In [1]:
import numpy as np
var = np.matrix([[1,2],[1,2]])
var1 = np.matrix([[1,2],[1,2]])
print(var + var1)
print(var - var1)
print(var.dot(var1))
print(type(var))

[[2 4]
 [2 4]]
[[0 0]
 [0 0]]
[[3 6]
 [3 6]]
<class 'numpy.matrix'>


In [4]:
x = np.matrix([[1,2,3],[4,5,6]])
print(x)
print()
print(np.transpose(x))
print()
print(x.T)
print()
print(np.swapaxes(x,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [5]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [6]:
var4 = np.matrix ([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.matrix_power(var4,2))
print()
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [7]:
var5 = np.matrix([[1,2],[3,4]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-2.0000000000000004


In [8]:
var6 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var6)
print()
print(np.linalg.det(var6))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
