In [6]:
import numpy as np
vaar = np.random.rand(4)
print(vaar)

[0.06865139 0.22120876 0.18603817 0.06049682]


In [5]:
vaar = np.random.rand(7)
print(vaar)

[0.67004199 0.82052891 0.99361772 0.78881483 0.99585539 0.67149405
 0.20003525]


In [9]:
var = np.random.randn(2,5)
print(var)

[[ 1.60088273 -1.11161766 -0.18277892 -0.63309011 -1.08110281]
 [-0.15591666  0.06997767 -2.09205028 -0.60691382  1.95396327]]


In [2]:

var1 = np.random.randn(5)

print(var1)

[ 1.55096899 -1.34437913 -1.24219857  0.14479512  0.61886749]


In [15]:
print()
x = int(input("enter a value"))
print()
var2 = np.random.ranf(x)
print(var2)

enter a value 5



[0.12456709 0.86229888 0.35011653 0.06922281 0.57617347]


In [8]:
var3 = np.random.randint(1,10,10)
print(var3)

[9 2 5 5 2 6 8 9 1 8]


In [16]:
var3 = np.random.randint(1,100,50)
print(var3)

[12 32 15 10 25 71 78 84 18 23 52 81 71 34 30 45 65 26  3 15  7 68 39 49
 56 80 66  2 99 13 53 54 90 41 67 38 86 34 13 80 10 39 60 74  4 46 30  2
 98 78]
