In [5]:
import numpy as np
var = np.array([[1,2,3,4],[1,2]])
print(var.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [8]:
var = np.array([1,2,3,4],ndim=4)
print(var)
print(var.ndim)
print(var.shape)

TypeError: array() got an unexpected keyword argument 'ndim'

In [9]:
var2 = np.array([1,2,3,4,5,6])
x = var2.reshape(3,2)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
var2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)
x1 = var2.reshape(2,3,2)
print(x1)
print(x1.ndim)
one = x1.reshape(-1)
print(one)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
