In [1]:
import numpy as np

# Create a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])

# Slice elements from index 1 to 3 (exclusive)
slice_1d = arr_1d[1:4]

print("Original 1D array:", arr_1d)
print("Sliced 1D array:", slice_1d)


Original 1D array: [10 20 30 40 50]
Sliced 1D array: [20 30 40]


In [2]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Slice the first two rows and the first two columns
slice_2d = arr_2d[:2, :2]

print("Original 2D array:")
print(arr_2d)
print("Sliced 2D array:")
print(slice_2d)


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced 2D array:
[[1 2]
 [4 5]]


In [3]:
import numpy as np

# Create a 3D array
arr_3d = np.array([[[ 1,  2,  3], 
                    [ 4,  5,  6]],

                   [[ 7,  8,  9], 
                    [10, 11, 12]],

                   [[13, 14, 15], 
                    [16, 17, 18]]])

# Slice the first two layers, all rows, and the first two columns
slice_3d = arr_3d[:2, :, :2]

print("Original 3D array:")
print(arr_3d)
print("Sliced 3D array:")
print(slice_3d)


Original 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Sliced 3D array:
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
